### ISSUE TITLE
Variation with no description doesn't blank description

### ISSUE THREAD

**Issue by timothy-h** [growdev/woocommerce-variation-description#10]
When you have a variation selected on the front end it shows that variation's descriptions; when you then select another variation that has no description, it still shows the description of the first variation, rather than hide the description.

**Comment by growdev** [comment]
Hi @timothy-h,  The description should change when the variation choice changes. Here's a demo:
http://esp.im/0p223n440y1s

Check that there are no javascript error on the page.
