### ISSUE TITLE
Html description

### ISSUE THREAD

**Issue by TeeAche** [growdev/woocommerce-variation-description#12]
Hi,
Thanks for your awesome job.

Is there any way to enter html text in the description textarea? So we would be able to display a formatted text.

Thank a lot!

**Comment by growdev** [comment]
Hi @TeeAche The variation is put inside a div with a class of `variation-description` so I'd suggest using CSS to style the text. 

![screen shot 2015-07-16 at 9 53 45 am](https://cloud.githubusercontent.com/assets/290886/8726555/936b815e-2ba0-11e5-8c26-01b2fcf1a8e4.png)
