### ISSUE TITLE
Data that is put into the description box is not saving when the product page is updated

### ISSUE THREAD

**Issue by joshdanielsjr** [growdev/woocommerce-variation-description#7]
The information that is placed in the description box is not being saved when the page is updated.

**Comment by growdev** [comment]
Hey Josh,  
Thanks for the issue.  I just pushed a change to the plugin and should have a version 1.0.0 soon.  If you still can't get it to save, let me know what version of WC you're on, and anything relevant to your install. 

Thanks!

**Comment by sudolcious** [comment]
Hey,
first of all: Great plugin! Appreciate the work. Sadly, it's not working for me either, instead it displays "YOLO!!!!". I'm on Wordpress 4.0.1 with WooCommerce 2.3.7.

**Comment by growdev** [comment]
Hey @sudolcious!   I'll be done soon and will ping you when it's ready!

**Comment by sudolcious** [comment]
Thanks a lot!

**Comment by growdev** [comment]
@joshdanielsjr @sudolcious The plugin is now functional :)  Please try it out and let me know if you find any issues.
